#!/bin/bash

######################################################################
#
#  Copyright (c) 2015 arakasi72 (https://github.com/arakasi72)
#
#  --> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
######################################################################

PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/bin:/sbin

rundir=$(dirname $(readlink -f $0))
branch=$1

# function to ask user for y/n response
ask_user(){
local answer
while true
  do
    read answer
    case $answer in [Yy]* ) return 0 ;;
                    [Nn]* ) return 1 ;;
                        * ) echo "Enter y or n";;
    esac
  done
}

if [ "$(id -u)" != "0" ]; then
  echo "Must be run as root, directly or with sudo"
  exit 1
fi

# kill apt-daily.service if running 
if [[ $(systemctl list-units --all apt-daily.service | fgrep -c apt-daily.service) -gt 0 ]]; then
  systemctl stop apt-daily.service > /dev/null 2>&1
  systemctl kill --kill-who=all apt-daily.service > /dev/null 2>&1

# wait until `apt-get updated` has been killed
  while ! (systemctl list-units --all apt-daily.service | fgrep -q dead)
    do
      sleep 1;
    done
fi

apt-get -qq update

if [ $(dpkg-query -W -f='${Status}' git 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
echo "Installing git"
apt-get -yqq install git 2>&1 >> /dev/null
fi

if [ $(dpkg-query -W -f='${Status}' ca-certificates 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
echo "Installing ca-certificates"
apt-get -yqq install ca-certificates 2>&1 >> /dev/null
fi




echo "Installing rtinst $branch"
cd
rm -rf /etc/rtinst
git clone https://github.com/c4pt000/rtinst.git /etc/rtinst
cd /etc/rtinst
ln -sf /etc/rtinst/scripts/* /usr/bin
ln -sf /etc/rtinst/rtsetup /usr/bin

echo "Installation complete"
echo
echo "You can now run rtinst and the additional supporting scripts"

